### ISSUE TITLE
Need to move default pins to NC

### ISSUE THREAD

**Issue by LMESTM** [ithinuel/STMOD_CELLULAR#6]
Otherwise the lib would not compile for targets that do no have STMOD connector.

A solution could be to default those pins to NC and use config specific to this target in mbed_lib.json. 
Use same method as here:
https://github.com/ARMmbed/wifi-ism43362/blob/master/mbed_lib.json

**Comment by jeromecoutant** [comment]
Discussion started in https://github.com/ARMmbed/mbed-os-example-cellular/pull/142
